services:
  api:
    build: .
    ports:
      - '3006:3006'
    depends_on:
      - feedback_db
    environment:
      DB_HOST: feedback_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: feedbackdb
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672
    networks:
      - app-network

  feedback_db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: feedbackdb
    ports:
      - '5433:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    external: true

volumes:
  postgres-data:
